server.port=8080

spring.application.name=geolocation-feasibility-api

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.bia.geolocationfeasibility=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html